

- hosts: testhosts
  gather_facts: no
  tasks:
    - name: Install apache2
      package:
        name: apache2
        state: present

    - name: Enable existing module
      apache2_conf:
        item: module
        name: deflate
        state: present

    - name: Re-Enable existing module
      apache2_conf:
        item: module
        name: deflate
        state: present

    - name: Disable existing module
      apache2_conf:
        item: module
        name: deflate
        state: absent

    - name: Enable again existing module
      apache2_conf:
        item: module
        name: deflate
        state: present

    - name: Enable non-existent module
      apache2_conf:
        item: module
        name: deflatenonexist
        state: present
